server:
  port: 8090
spring:
  application:
    name: sdn-monitor
  datasource:
    url: ${URL_DB}
    username: ${USER_NAME}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

sdn:
  influxdb:
    host: http://localhost:8086
    database: ryu_monitor
    poll-interval-ms: 10000
  prometheus:
    host: http://localhost:9090
    poll-interval-ms: 15000
  ryu:
    host: http://localhost:8080
  anomaly:
    ddos-critical-threshold: 1000
    ddos-high-threshold: 500
    check-interval-ms: 5000

cors:
  allowed-origins: "http://localhost:3001"

logging:
  level:
    com.sdn.monitor: DEBUG
    org.springframework.web.socket: INFO