FROM ubuntu:22.04

WORKDIR /root

COPY infra/docker/entrypoint-mininet.sh /ENTRYPOINT.sh

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl \
        dnsutils \
        ifupdown \
        iperf3 \
        iproute2 \
        iptables \
        iputils-ping \
        mininet \
        nano \
        netcat-openbsd \
        net-tools \
        openvswitch-switch \
        python3-pip \
        tcpdump \
        tshark \
        x11-xserver-utils \
        xterm \
        hping3 \
        nmap \
        build-essential \
        libssl-dev \
        git \
        autoconf \
        automake \
        libtool \
        pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && touch /etc/network/interfaces \
    && chmod +x /ENTRYPOINT.sh \
    && cd /tmp \
    && git clone https://github.com/shekyan/slowhttptest.git \
    && cd slowhttptest \
    && ./configure \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/slowhttptest

RUN pip3 install --break-system-packages mininet pyaml

EXPOSE 6633 6653 6640

ENTRYPOINT ["/ENTRYPOINT.sh"]